version: '3.7'
services:
    authenticator:
        build:
            context: ./deploy
        ports:
            - 80:80
    flask-app:
        build: 
            context: ./deploy/app
        volumes:
            - ./src:/app
        expose:
            - "5000"

